### PR TITLE
RawJsonWithMetadataSourceHandler - add collection and scope names

### PR DESCRIPTION
**Pull request by avihaim**

### CODE REVIEW

**Comment by dnault** [comment]
Hi @avihaim  -- thanks for this. We've been considering having `RawJsonSourceHandler` and `RawJsonWithMetadataSourceHandler` include the scope and collection name as Kafka record headers. Would that meet your requirement?

**Comment by avihaim** [comment]
> Hi @avihaim -- thanks for this. We've been considering having `RawJsonSourceHandler` and `RawJsonWithMetadataSourceHandler` include the scope and collection name as Kafka record headers. Would that meet your requirement?

Yes, I guess I will be able to take this info from the headers and add it to my massage intarnliy.
Just from curiosity, why in the headers and not in the massage?

**Comment by dnault** [comment]
Just from curiosity, why in the headers and not in the massage?

If we use headers, then `RawJsonSourceHandler` can benefit as well as `RawJsonWithMetadataSourceHandler`

**Comment by dnault** [comment]
Tracking as [KAFKAC-362](https://jira.issues.couchbase.com/browse/KAFKAC-362)

**Comment by dnault** [comment]
Code review on Gerrit: https://review.couchbase.org/c/kafka-connect-couchbase/+/219552

**Comment by dnault** [comment]
kafka-connect-couchbase version 4.2.5 has been released, with support for including scope and collection (and other metadata) as Kafka record headers. 

There's a new source connector config option for specifying which headers to set:
https://docs.couchbase.com/kafka-connector/current/source-configuration-options.html#couchbase.headers

The header name prefix is configurable (defaults to "couchbase.")
https://docs.couchbase.com/kafka-connector/current/source-configuration-options.html#couchbase.header.name.prefix

@avihaim Please can you try this and confirm whether it meets your requirements? Thanks!

**Comment by dnault** [comment]
@avihaim Apologies -- a failure on my part lead to a problem that prevents version 4.2.5 from being usable. Please be on the lookout for a 4.2.6 shortly.

**Comment by dnault** [comment]
The 4.2.6 binaries are up. Revised release notes will be online soon. In the meantime, here's a direct download link: [couchbase-kafka-connect-couchbase-4.2.6.zip](https://packages.couchbase.com/clients/kafka/4.2.6/couchbase-kafka-connect-couchbase-4.2.6.zip)

**Comment by dnault** [comment]
Thanks again @avihaim . It's been a while without activity, so I'll close this PR. Please follow up with a separate issue / PR if the header-based solution added in 4.2.6 doesn't work for you.

**Pull request closed without merging**
