### PR TITLE
rework docs to be compatible with Antora (release/3.3)

### PR DESCRIPTION
**Pull request by mojavelinux**
- add document titles
- set component name to kafka-connector
- set component title to Kafka Connector
- add missing introduction / index page
- move images out of kafka folder
- remove _attributes.adoc file
- move nav items into category
- apply sentence per line formatting
- fix page references
- remove explicit start page
- use proper admonition blocks

### CODE REVIEW

**Comment by dnault** [comment]
Hi Dan, Thanks for this. Do please create a Gerrit account using the link above and sign the CLA so the robot will import your changes into Gerrit. Make sure to use the `d**s@couc*****.com` address when signing up so it can associate your this pull request with your account.
Cheers,
David

**Comment by mojavelinux** [comment]
David,

I accepted the agreement. However, I don't understand the part about the e-mail address. Why would I use an e-mail address that isn't mine? That seems counter-intuitive.

**Comment by dnault** [comment]
Oh, you're right! Sorry, I didn't realize the address on the commit wasn't yours. I think we have a process issue to sort out...

**Comment by mojavelinux** [comment]
Oh, I see the problem now. Actually, that's probably my fault. I committed as the robot, but I didn't have to do that in this case. I can amend the commit so the author is my account. Shall I proceed with that?

**Comment by dnault** [comment]
Yes, please. Thanks!

**Comment by mojavelinux** [comment]
Updated!

**Comment by mojavelinux** [comment]
It looks like the Gerrit integration doesn't respect the target branch specified in the PR. This change should be targeting releases/3.3 instead of master (there's another one for master).

**Comment by dnault** [comment]
I've submitted a help request for the branch mismatch issue. In the mean time, are you comfortable sending the change directly to Gerrit? If not, let me know and I'll amend the commit to use my email address and submit it to the correct branch on your behalf. If you want to take the plunge, here are the setup instructions:

SSH key setup:
 *    Go through gerrit's Settings screen and set up your SSH keys. IMPORTANT: - do not forget to setup your username on the Settings screen.
*    Again, the username setup in gerrit -> Settings -> SSH Keys (http://review.couchbase.org/#settings,ssh-keys) is important. Folks have been bitten for not doing the username setup while setting up SSH keys.
*    Add an entry for review.couchbase.org to your .ssh/config file:

    Host review.couchbase.org
        HostName review.couchbase.org
        Port 29418
        User <GERRIT_USERNAME>


Then from the `cb-docs-review-space/kafka-connect-couchbase` project directory:

    git remote add gerrit ssh://<GERRIT_USERNAME>@review.couchbase.org:29418/kafka-connect-couchbase

And finally, to submit the commits on the current local branch for review:

    git push gerrit HEAD:refs/for/<TARGET_BRANCH_NAME>

So in this case:

    git checkout release/3.3-patched
    git push gerrit HEAD:refs/for/release/3.3

**Comment by dnault** [comment]
Looks like it might take a while for the branch targeting issue to be resolved, so I've submitted to Gerrit on @mojavelinux's behalf: http://review.couchbase.org/#/c/98839/

**Comment by dnault** [comment]
Original Gerrit change was abandoned because of the target branch issue. The Gerrit change targeting the correct branch has been merged.

**Comment by mojavelinux** [comment]
Thank you @dnault! I appreciate your efforts to get this resolved this swiftly. We can now proceed with consuming the docs directly from this repository for the new site.

**Pull request closed without merging**
