### PR TITLE
KAFKAC-98 Added multi-mutation support

### PR DESCRIPTION
**Pull request by werkins**

### CODE REVIEW

**Comment by avsej** [comment]
@werkins, I left review notes on gerrit change, could you update the patch there?

**Comment by avsej** [comment]
@werkins, please use gerrit to update the patch.

**Comment by avsej** [comment]
@werkins github will not help you to create the patch for review properly. You have to use gerrit to submit updates.

**Comment by dnault** [comment]
Hi @werkins,

Just wanted to see if you were able to make the changes mentioned over on the Gerrit PR. Let us know if you want help with Gerrit or something else.

Thanks,
David

**Comment by werkins** [comment]
I'm sorry guys, but I've been lately too busy to polish the code. Most of the work is already done, just need to find a couple of hours for it (still difficult, though)

**Comment by dnault** [comment]
Closing due to inactivity. We appreciate the work you put into this, and would be happy to pick it up again if you'd like to resume working on it in the future.

**Pull request closed without merging**
