### PR TITLE
Add health check couchbaseReader

### PR DESCRIPTION
**Pull request by tiny1990**
Add health checkout in poll method.
Throw exception if couchbaseReader dead.
We can get exception message  use rest api /connectors/xxx/status.

### CODE REVIEW

**Comment by tiny1990** [comment]
@avsej  @dnault review pr  plz

**Comment by dnault** [comment]
Thanks @tiny1990, this seems like a nice improvement. We'll review in depth and report back. In the mean time, would you mind squashing the 3 commits into 1?

**Comment by brett19** [comment]
test

**Comment by brett19** [comment]
*poke*

**Comment by tiny1990** [comment]
@dnault   PR reviewed?

**Comment by dnault** [comment]
This improvement is included in Kafka Connect Couchbase 3.2.2 which was released today.

**Pull request closed without merging**
